version: '3.7'
services:
  nats:
    container_name: tails-nats
    image: nats:2.1
    expose:
      - 6222
    ports:
      - target: 4222
        published: 4222
      - target: 8222
        published: 8222
    privileged: false
  dashboard-mpa:
    container_name: tails-dashboard-mpa
    image: node:12-slim
    user: 1000:1000
    working_dir: /opt/app
    command: npm run serve
    volumes:
      - type: bind
        source: ./dashboard-mpa
        target: /opt/app
    ports:
      - target: 3010
        published: 3010
    expose:
      - 3010
    environment:
      NODE_ENV: development
      PORT: 3010
    links:
      - nats
      - editor
      - operator
    privileged: false
  editor:
    container_name: tails-editor
    image: node:12-slim
    user: 1000:1000
    working_dir: /opt/app
    command: npm run serve
    volumes:
      - type: bind
        source: ./editor
        target: /opt/app
      - type: bind
        source: ./projects
        target: /opt/app/projects
    ports:
      - target: 3030
        published: 3030
    environment:
      NODE_ENV: development
      PORT: 3030
    links:
      - nats
  operator:
    container_name: tails-operator
    image: node:12-slim
    user: 1000:1000
    working_dir: /opt/app
    command: npm run serve
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./operator
        target: /opt/app
    ports:
      - target: 3020
        published: 3020
    expose:
      - 3020
    environment:
      NODE_ENV: development
      PORT: 3020
    links:
      - nats
    privileged: false
  documentation:
    container_name: tails-documentation-site
    image: node:12-slim
    user: 1000:1000
    working_dir: /opt/app/website
    command: npm run serve
    volumes:
      - type: bind
        source: ./documentation/docs
        target: /opt/app/docs
      - type: bind
        source: ./documentation/site
        target: /opt/app/website
    ports:
      - target: 2990
        published: 2990
    environment:
      NODE_ENV: development
      PORT: 2990
    privileged: false
  debug:
    container_name: tails-debug
    image: node:12-slim
    working_dir: /opt/app/debug
    command: npm run serve
    volumes:
      - type: bind
        source: ./debug
        target: /opt/app/debug
    environment:
      NODE_ENV: development
    privileged: false
